name = "MimiIWG"
uuid = "b1d80750-afbf-11e9-0666-4f25b2ea2b65"
version = "1.2.0"

[deps]
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
CSVFiles = "5d742f6a-9f54-50ce-8119-2520741973ca"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
Query = "1a8c2f83-1ff3-5112-b086-8aa67b057ba1"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
MimiPAGE2009 = "e25d4f70-4200-11e9-37f3-3b45f1cef54f"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Mimi = "e4e893b0-ee5e-52ea-8111-44b3bdec128c"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
XLSX = "fdbf4ff8-1666-58a4-91e7-1b58723a45e0"
MimiFUND = "b3ba11de-429f-11e9-29f7-cb478ab96e7c"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
MimiDICE2010 = "4f2c5d70-42a7-11e9-1de8-c370bd984083"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1.4"
StatsBase = "0.33"
XLSX = "0.7.3"
MimiPAGE2009 = "3.0"
Distributions = "0.23, 0.24, 0.25"
Mimi = "1.3"
MimiFUND = "=3.8.6"
Interpolations = "0.13"
MimiDICE2010 = "1.0"

[targets]
test = ["Test"]
